<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>PresetMaestro</AssemblyName>
    <AssemblyTitle>Preset Maestro</AssemblyTitle>
    <RootNamespace>PresetMaestro</RootNamespace>
    <Product>Preset Maestro</Product>
    <Title>Preset Maestro</Title>
    <ApplicationIcon>preset_maestro.ico</ApplicationIcon>
    <PublishDir>..\publish\</PublishDir>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="preset_maestro.ico" />
    <ProjectReference Include="..\PresetNameSync.Core\PresetNameSync.Core.csproj" />
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

</Project>
